# Generated by Django 5.1.1 on 2025-08-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
