# Generated by Django 5.1.1 on 2025-08-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_day_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='date',
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='name',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.IntegerField(),
        ),
    ]
